# Generated by Django 5.0.6 on 2024-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.SlugField(default=True, max_length=6),
        ),
    ]
